version: "{build}"

build: off

environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0    # will fetch the latest node.js version
    - nodejs_version: 1    # will fetch the latest io.js version

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - cmd: set
  - ps: Write-Host 'This is PowerShell'
  - ps: npm install --msvs_version=2013
